config/routes.rb
Rails.application.routes.draw do

  resources :users do
    collection do
      get :login
      get :attempt_login
      get :logout
    end
  end

  resources :tasks do
    member do
      get :delete
    end
  end

  root 'entry#index'

end

app/models/task.rb
class Task < ActiveRecord::Base

  validates_presence_of :name
  validates_length_of :name, :minimum => 3, :maximum => 8
  validates_uniqueness_of :name, :case_sensitive=>false
  validate :name_not_in_black_list

  def self.completed
    where :completed => true
  end

  def self.uncompleted
    where :completed => false
  end

  private
  def name_not_in_black_list
    if not name.nil? and name.include? 'puncha'
      errors.add :name, 'should not contain puncha'
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  private

  def check_logged_in
    if session[:username].nil?
      flash[:errors] = ['Please log in first.']
      redirect_to '/'
      return false # stop bubbling
    else
      return true
    end
  end
end

app/controllers/entry_controller.rb
class EntryController < ApplicationController
  def index
  end
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  respond_to :html, :xml, :json
  skip_before_filter :verify_authenticity_token, if: :json_request?
  before_action :check_logged_in, :except => []

  def index
    filter = params[:filter] || 'all'
    case filter
      when 'all' then @tasks = Task.all
      when 'completed' then @tasks = Task.completed
      when 'uncompleted' then @tasks = Task.uncompleted
      else @tasks = []
    end

    respond_with @tasks
  end

  def show
    respond_with do |format|
      format.json { render :json => Task.all }
    end
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new task_params
    if @task.save
      flash[:notice] = "New task '#{task_params[:name]}' created."
    else
      flash[:errors] = ["Failed to create new task '#{task_params[:name]}'."]
      flash[:errors] += @task.errors.full_messages
    end
    respond_with @task, location: tasks_path
  end

  def edit
    id = params[:id]
    @task = Task.find id
  end

  def update
    @task = Task.find params[:id]
    if @task.update_attributes task_params
      flash[:notice] = 'Task is updated.'
    else
      flash[:errors] = ["Failed to update task '#{task_params[:name]}'."]
      flash[:errors] += @task.errors.full_messages
    end
    respond_with @task, location: tasks_path do |format|
      format.json { render :json => {bab:'god'}.to_json }
    end
  end

  def delete
    @task = Task.find params[:id]
    succ = @task.destroy
    if succ
      flash[:notice] = 'Task is deleted.'
    else
      flash[:errors] = ["Failed to delete task '#{@task.name}'."]
      flash[:errors] += task.errors.full_messages
    end
    respond_to do |format|
      format.html { redirect_to tasks_url(filter:params[:filter]) }
      format.json { return {:result=>succ} }
    end
  end

  def destroy
    delete
  end


  private

  def task_params
    params.require(:task).permit(:name, :completed)
  end

  def json_request?
    request.accepts.each do |content_type|
      if content_type == 'application/html' or content_type == 'application/xml'
          return false
      elsif 'application/json'
        return true
      end
    end
    return false
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  before_action :check_logged_in, :only => [:logout]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def login
    @user = User.new
    @user.username = cookies[:username]
    @user.password = cookies[:password]
  end

  def attempt_login
    user = user_params
    dbUser = User.where(user).first
    if dbUser
      cookies[:username] = user[:username]
      cookies[:password] = user[:password]
      session[:username] = dbUser.username
      flash[:notice] = "#{session[:username]}, you are successfully logged in."
      redirect_to '/'
    else
      cookies[:username] = cookies[:password] = nil
      flash[:errors] = ['Username or password is wrong. Please retry.']
      @user = User.new user
      @user.errors.add (:username)
      @user.errors.add (:password)
      render 'login'
    end
  end

  def logout
    session[:username] = nil
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:username, :password, :email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def bootstrap_flash_notice
    unless flash[:notice].nil?
      render :partial=>'helper_fragments/flash_notice', :locals=>{notice:flash[:notice]}
    end
  end

  def bootstrap_flash_errors
    errors = flash[:errors]
    unless errors.nil? or errors.empty?
      render :partial=>'helper_fragments/flash_errors', :locals=>{errors:errors}
    end
  end
end

app/helpers/entry_helper.rb
module EntryHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/entry/index.html.erb
<div class="jumbotron">
  <div class="container">
    <h1>TODO List</h1>
    <p>A Rail4 application.</p>
  </div>
</div>

app/views/helper_fragments/_flash_errors.html.erb
<div class='alert alert-danger alert-dismissible fade in' role='alert'>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">×</span>
  </button>
  <ul class="panel-body">
    <% errors.each do |err| %>
      <li><%= err %></li>
    <% end %>
  </ul>
</div>

app/views/helper_fragments/_flash_notice.html.erb
<div class="alert alert-info alert-dismissible fade in" role="alert">
  <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
  <%= notice %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title><%= content_for?(:title) ? yield(:title) : 'RailsTodoList' %></title>
  <%= csrf_meta_tags %>

  <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
  <!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
  <![endif]-->

  <%= stylesheet_link_tag 'application', :media => 'all' %>

  <!-- For third-generation iPad with high-resolution Retina display: -->
  <!-- Size should be 144 x 144 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

  <!-- For iPhone with high-resolution Retina display: -->
  <!-- Size should be 114 x 114 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

  <!-- For first- and second-generation iPad: -->
  <!-- Size should be 72 x 72 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

  <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
  <!-- Size should be 57 x 57 pixels -->
  <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

  <!-- For all other devices -->
  <!-- Size should be 32 x 32 pixels -->
  <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

  <%= javascript_include_tag 'application' %>
</head>
<body>

<div class="navbar navbar-default navbar-static-top">
  <div class="container">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-responsive-collapse">
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
      <span class="icon-bar"></span>
    </button>
    <a class="navbar-brand" href="/">Rails Todo List</a>
    <div class="navbar-collapse collapse navbar-responsive-collapse">
      <ul class="nav navbar-nav">
        <!--Tasks-->
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">View Tasks <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><%= link_to 'View all tasks', tasks_path(filter:'all') %></li>
            <li><%= link_to 'View uncompleted tasks', tasks_path(filter:'uncompleted') %></li>
            <li><%= link_to 'View completed tasks', tasks_path(filter:'completed') %></li>
          </ul>
        </li>
        <!--Users-->
        <li><%= link_to 'Manage users', users_path %></li>
      </ul>
    </div>
  </div>
</div>

<div class="container">
  <div class='panel panel-primary'>
    <p class="panel-heading">User</p>
    <ul class="panel-body" style="list-style: none;">
      <% username = session[:username] %>
      <% if not username %>
        <li>
          <%= link_to 'log in', login_users_path, 'class'=> 'btn btn-default' %>
        </li>
      <% else %>
        <li>
          <%= username %>
          <span class="btn-group btn-group-sm">
            <%= link_to 'log out', logout_users_path, 'class'=> 'btn btn-danger' %>
          </span>
        </li>
      <% end %>
    </ul>
  </div>
  <%= bootstrap_flash_errors %>
  <div class="row">
    <!--
        <div class="col-lg-3">
          <div class="well sidebar-nav">
            <h3>Sidebar</h3>
            <ul class="nav nav-list">
              <li class="nav-header">Sidebar</li>
              <li><%= link_to "Link1", "/path1"  %></li>
              <li><%= link_to "Link2", "/path2"  %></li>
              <li><%= link_to "Link3", "/path3"  %></li>
            </ul>
          </div>
        </div>
        -->
    <div class="col-lg-12">
      <%= bootstrap_flash_notice %>
      <%= yield %>
    </div>
  </div><!--/row-->

  <footer>
    <p>&copy; PunCha 2014</p>
  </footer>

</div> <!-- /container -->

</body>
</html>

app/views/tasks/_task_form.html.erb
<div class="form-group">
  <%= f.label :name, 'Name', class: 'col-sm-2 control-label' %>
  <div class="col-sm-2">
    <%= f.text_field :name, class:'form-control', placeholder: 'task name' %>
  </div>
</div>
<div class="form-group">
  <%= f.label :completed, 'Is Completed?', class: 'col-sm-2 control-label' %>
  <div class="col-sm-1">
    <%= f.check_box :completed, class:'form-control' %>
  </div>
</div>
<div class="form-group">
  <div class="col-sm-offset-2 col-sm-2">
    <%= submit_tag submit_btn_text || 'Submit', class:'btn btn-primary' %>
  </div>
</div>

app/views/tasks/edit.html.erb
<%= form_for(:task,
             :url=> task_url(params[:id]),
             :html=> { :method=>:patch, :class=>'form-horizontal'}) do |f| %>
  <%= render :partial => 'tasks/task_form', :locals => {f:f, submit_btn_text:'Update task'} %>
<% end %>

app/views/tasks/index.html.erb
<h1>Listing tasks</h1>
<%= link_to 'Create new', new_task_path, class:'btn btn-primary' %>
<hr/>


<table class="table">
  <thead>
  <tr>
    <th>Task</th>
    <th>Actions</th>
  </tr>
  </thead>

  <tbody>
    <% @tasks.each do |tsk| %>
    <tr>
      <td>
        <span class="glyphicon <%= tsk.completed ? 'glyphicon-saved' : 'glyphicon-unchecked' %>"></span>
        <label><%= tsk.name %></label>
      </td>
      <td>
        <div class="btn-group btn-group">
          <%= link_to 'Edit', edit_task_path(tsk.id), 'class'=>'btn btn-primary' %>
          <%= link_to 'Delete', task_path(tsk.id, filter:params[:filter]), :method =>:delete, 'class'=>'btn btn-danger' %>
        </div>
      </td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/tasks/new.html.erb
<%= form_for(:task,
             url:tasks_url,
             html:{class:'form-horizontal'}) do |f| %>
  <%= render :partial => 'tasks/task_form', :locals => {f:f, submit_btn_text:'Create task'} %>
<% end %>

app/views/tasks/show.html.erb
<h1>Task#show,</h1>
<p>Find me in app/views/task/show.html.erb</p>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>
<%= link_to 'Create new', new_user_path, class:'btn btn-primary' %>
<hr/>

<table class="table">
  <thead>
    <tr>
      <th>Username</th>
      <th>Password</th>
      <th>Email</th>
      <th>Actions</th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.username %></td>
        <td><%= user.password %></td>
        <td><%= user.email %></td>
        <td>
          <div class="btn-group btn-group">
            <%= link_to 'Show', user, class:'btn btn-primary' %>
            <%= link_to 'Edit', edit_user_path(user), class:'btn btn-success' %>
            <%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, class:'btn btn-danger' %>
          </div>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/users/login.html.erb
<h1>Log in</h1>

<%= form_for(@user, :url=>attempt_login_users_path(), :html=> {:method=>'get'}) do |f| %>
  <div class="field">
    <%= f.label :username %><br>
    <%= f.text_field :username %>
  </div>
  <div class="field">
    <%= f.label :password %><br>
    <%= f.text_field :password %>
  </div>
  <div class="actions">
    <%= f.submit 'Login in' %>
  </div>
<% end %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Username:</strong>
  <%= @user.username %>
</p>

<p>
  <strong>Password:</strong>
  <%= @user.password %>
</p>

<p>
  <strong>Email:</strong>
  <%= @user.email %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>